config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/help'
  get 'static_pages/home'

  resources :products do
    get :product_json, :on => :member
  end

  resources :clients do
    get :client_json, :on => :member
  end

  devise_for :users, :path_prefix => 'auth'
  resources :users, :only => [:show]

  resources :invoices, :except => [:edit, :update, :destroy] do
    get :set_paid,            :on => :member
    get :kreditnota,          :on => :member
    get :email_invoice,       :on => :member
    post :send_email_invoice, :on => :member
  end

  get 'invoice_items/destroy'

  ActiveAdmin.routes(self)
  get 'static_pages/home'

  # Set different roots for guest and logged in user
  authenticated :user do
    root 'invoices#index', :as => 'auth_root'
  end
  root 'static_pages#home'
end

app/models/invoice.rb
# Invoice model
class Invoice < ActiveRecord::Base
  # Default scopes
  default_scope { order('invoice_number DESC') }

  # Associations
  belongs_to :user
  belongs_to :client
  has_many :invoice_items, :inverse_of => :invoice, :dependent => :destroy
  accepts_nested_attributes_for :invoice_items, :allow_destroy => true,
                                                :reject_if     => :all_blank

  # Validations
  validates :user,             :presence => true
  validates :client,           :presence => true, :on => :save
  validates :invoice_items,    :presence => true
  validates :invoice_number,   :presence => true
  validates :currency,         :presence => true
  validates :delivery_date,    :presence => true
  validates :due_date,         :presence => true
  validates :client_name,      :presence => true
  validates :client_address,   :presence => true
  validates :delivery_address, :presence => true
  validates :total,            :presence => true, :on => :save

  # Callbacks
  before_save :store_user_data
  before_save :calculate_total
  before_save :save_client_if_new

  # Scopes
  scope :unpaid,       -> { where(:paid => false) }
  scope :overdue,      -> { unpaid.where('due_date < ?', Date.today) }

  def self.current_year
    dt = DateTime.new(2015)
    boy = dt.beginning_of_year
    eoy = dt.end_of_year
    where('created_at >= ? and created_at <= ?', boy, eoy)
  end

  # Duplicates the invoice and returns the copy. Needed
  # to make sure all items are duplicated for kreditnota.
  def replicate
    replica = dup
    invoice_items.each do |item|
      replica.invoice_items << item.dup
    end
    replica
  end

  def type
    kreditnota ? 'kreditnota' : 'faktura'
  end

  def to_s
    "#{type} #{invoice_number}"
  end

  private

  # Stores the needed user/sender information in the invoice object
  # rubocop:disable Metrics/AbcSize
  def store_user_data
    assign_attributes(:user_name         => user.name,
                      :user_org_number   => user.org_nr_with_registrations,
                      :user_email        => user.email,
                      :user_phone        => user.phone,
                      :user_bank_swift   => user.bank_swift,
                      :user_bank_iban    => user.bank_iban,
                      :user_bank_name    => user.bank_name,
                      :user_bank_account => user.bank_account,
                      :user_address      => user.address)
  end
  # rubocop:enable Metrics/AbcSize

  # Creates and assigns a new client if a client_id
  # is not specified for the invoice
  # rubocop:disable Metrics/AbcSize
  def save_client_if_new
    return unless client_id.blank?
    new_client = user.clients.new(:name             => client_name,
                                  :email            => client_email,
                                  :address          => client_address,
                                  :delivery_address => delivery_address,
                                  :ref              => client_ref,
                                  :org_nr           => client_org_nr)
    # rubocop:enable Metrics/AbcSize

    # saves the client and assigns its id to self
    return unless self.valid?
    new_client.save
    self[:client_id] = new_client.id
  end

  # Calculates and stores the invoice total
  def calculate_total
    total = 0.0
    invoice_items.each do |i|
      total += (i.quantity * i.unit_price * ((i.vat.to_f / 100) + 1))
    end
    self[:total] = total
  end
end

app/controllers/invoices_controller.rb
# Actions related to invoices
class InvoicesController < ApplicationController
  # Authenticate with Devise, Authorize with CanCanCan
  before_action :authenticate_user!
  load_and_authorize_resource

  # rubocop:disable Metrics/AbcSize
  # rubocop:disable Metrics/MethodLength
  def index
    @invoices = current_user.invoices

    case params[:filter]
    when 'unpaid'
      @invoice_list = current_user.invoices.unpaid.paginate(
        :per_page => 25, :page => params[:page])
    when 'overdue'
      @invoice_list = current_user.invoices.overdue.paginate(
        :per_page => 25, :page => params[:page])
    else
      @invoice_list = current_user.invoices.paginate(
        :per_page => 25, :page => params[:page])
    end
  end
  # rubocop:enable Metrics/AbcSize
  # rubocop:enable Metrics/MethodLength

  def new
    @client_list = current_user.clients.map { |c| [c.name, c.id] }
    @invoice = current_user.invoices.new(
      :invoice_number => current_user.next_invoice_number,
      :invoice_items  => [InvoiceItem.new])
  end

  def create
    @invoice = current_user.invoices.new(invoice_params)
    if @invoice.save
      current_user.increment!(:next_invoice_number)
      redirect_to @invoice
    else
      render 'new'
    end
  end

  def show
    @invoice = current_user.invoices.find(params[:id])

    # Render html for online view or pdf for download
    respond_to do |format|
      format.html
      format.pdf do
        render :pdf         => "faktura_#{@invoice.invoice_number}",
               # Unncomment next line to force download instead of browser
               # view. This will break loading spinner.
               # :disposition => 'attachment',
               :encoding    => 'utf8'
      end
    end
  end

  # Renders _email_invoice.html.erb via email_invoice.js.erb
  def email_invoice
    @invoice = current_user.invoices.find(params[:id])
  end

  # Gets called by _email_invoice.html.erb submit button
  def send_email_invoice
    @invoice = current_user.invoices.find(params[:id])
    UserMailer.pdf_email(@invoice, params[:message]).deliver_now
    @invoice.increment!(:sends)
    flash[:notice] = 'Faktura er sendt til kunde.'
    redirect_to invoices_path
  end

  # Javascript reloads needed parts of view
  def set_paid
    @invoice = Invoice.find(params[:id])
    @invoice.toggle!(:paid)
    redirect_to :back
  end

  def kreditnota
    @to_credit = current_user.invoices.find(params[:id])
    @invoice = @to_credit.replicate
    @invoice.assign_attributes(
      :notes          => "Kreditnota for faktura #{@to_credit.invoice_number}",
      :kreditnota     => true,
      :invoice_number => current_user.next_invoice_number)
  end

  private

  # Helper method to increase invoice sends on send_email_invoice
  def increment_sends(invoice)
    invoice.update_attribute(:sends, invoice.sends + 1)
  end

  # Strong parameters
  def invoice_params
    params.require(:invoice).permit(
      :notes, :client_id, :user_name, :user_org_number, :user_email,
      :user_phone, :user_bank_swift, :user_bank_iban, :user_bank_name,
      :user_bank_account, :user_address, :user_ref, :invoice_number,
      :kreditnota, :due_date, :order_date, :delivery_date, :total, :currency,
      :paid, :client_name, :client_email, :client_address, :delivery_address,
      :client_ref, :client_org_nr,
      :invoice_items_attributes => [:id, :description, :quantity, :vat, :unit,
                                    :unit_price, :total, :user_id, :invoice_id,
                                    :_destroy])
  end
end

app/helpers/invoices_helper.rb
# Helper for invoice views
module InvoicesHelper
  # Returns a bootstrap label class based on count
  def overdue_label_color
    current_user.invoices.overdue.count == 0 ? 'label-success' : 'label-danger'
  end

  # returns total amount for overdue invoices for current user
  def overdue_amount
    amount = 0.00
    current_user.invoices.overdue.each do |i|
      amount += i.total
    end
    amount
  end

  # returns total amount and currency for invoices in given array
  def subtotal(invoices)
    amount = 0.00
    invoices.each do |i|
      if i.kreditnota
        amount -= i.total
      else
        amount += i.total
      end
    end
    number_to_currency(amount)
  end

  # returns sum of unpaid invoices
  def unpaid_amount
    amount = 0.00
    current_user.invoices.unpaid.each do |i|
      amount += i.total
    end
    amount
  end

  # To mark overdue invoices table row in red
  def rowcolor(invoice)
    if !invoice.paid && (DateTime.now.to_date > invoice.due_date)
      return 'danger'
    else
      ''
    end
  end

  # Calculates and returns 'momsgrunnlag' for the given invoice/percentage
  def finn_grunnlag(invoice, percent)
    items = []
    grunnlag = 0

    # Collect items with specified vat
    invoice.invoice_items.each do |item|
      items << item if (item.vat == percent)
    end

    # Sum price x quantity for all items
    items.each do |item|
      grunnlag += (item.unit_price * item.quantity)
    end
    grunnlag
  end

  # Returns true if the given invoice has items with multiple vat percentages
  def multiple_mva(invoice)
    satser = 0

    [0, 8, 15, 25].each do |vat|
      satser += 1 if finn_grunnlag(invoice, vat) > 0
    end
    satser > 1
  end
end

app/views/invoices/_email_invoice.html.erb
<div class="modal-content">
    <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Send Faktura</h4>
    </div>
    <div class="modal-body">

        <% if @invoice.sends != 0 %>
            <div class="alert alert-danger" role="alert">
                Denne <%= @invoice.type %>en er allerede sendt. Er du sikker på at du vil sende på nytt?
            </div>
        <% end %>

        <%= form_tag(send_email_invoice_invoice_path) do %>

            <div class="panel panel-default">
                <div class="panel-heading">
                    <div class="muted">
                        <small>
                        <b>Til: </b><%= @invoice.client.name %> &lt;<%= @invoice.client.email %>&gt;<br>
                        <b>Fra: </b><%= @invoice.user.name %> &lt;<%= @invoice.user.email %>&gt;<br>
                        <b>Blindkopi: </b><%= @invoice.user.name %> &lt;<%= @invoice.user.email %>&gt;<br>
                        <b>Vedlegg: </b><%= @invoice.to_s %>.pdf
                        </small>
                    </div>
                </div>
                <div class="panel-body">

                    <h1><%= @invoice.to_s.capitalize %></h1>

                    <div class="form-group">
                        <%= text_area_tag 'message', (@invoice.notes + "\n\n" + "Mvh,\n" + @invoice.user.name), class: 'form-control', rows: 6,
                            placeholder: 'Beskjed til mottaker.', autofocus: true %>
                    </div>

                    <u><b>Oppsummering:</u></b><br>
                    <%= @invoice.type.capitalize %>nummer: <%= @invoice.invoice_number %><br>
                    Fra: <%= @invoice.user.name %><br>
                    Forfallsdato: <%= @invoice.kreditnota ? '--/--/----' : @invoice.due_date.strftime('%d/%m/%Y') %><br>
                    <% unless @invoice.kreditnota %>
                        Kontonummer: <%= @invoice.user.bank_account %><br>
                    <% end %>
                    Totalt <%= @invoice.kreditnota ? 'kreditert' : 'å betale' %>:  <%= number_with_precision(@invoice.total, :precision => 2) %> <%= @invoice.currency %><br><br>


                    <p>
                        ---<br>
                        <%= @invoice.type.capitalize %> er vedlagt i pdf-format.<br>
                        <em>Sendt med <a href="http://www.barefaktura.no">BareFaktura.no</a></em><p>
                    </p>


                </div>
            </div>

            <%= hidden_field_tag 'id', @invoice.id %>

            <button type="button" class="btn btn-default" data-dismiss="modal">Lukk</button>
            <%= submit_tag 'Send faktura', class: 'btn btn-primary send-pdf-email' %>
       <% end %>
    </div>
</div>

app/views/invoices/email_invoice.js.erb
$("#email-invoice-modal").html("<%= escape_javascript(render 'email_invoice') %>");

app/views/invoices/index.html.erb
<h1>Faktura</h1>
<%= render partial: 'invoices/partials/summary' %><br>
<p><%= link_to '+ Ny Faktura', new_invoice_path, class:'btn btn-default btn-block' %></p><br>
  <div id="invoice-list">
    <%= render partial: 'invoices/partials/invoice_list' %>
  </div>

app/views/invoices/kreditnota.html.erb
<h1>Ny Kreditnota</h1>
<p>Dersom hele den opprinnelige fakturaen skal krediteres klikker du bare lagre. Dersom kun deler av fakturaen skal krediteres endrer du antall og/eller pris på varene slik at det reflekterer hvor mye som skal krediteres. Regnskapsmessig er det enkleste som oftest å kreditere hele fakturaen og deretter lage en ny faktura med riktig informasjon.</p>

<%= javascript_tag do %>
  userProducts = <%= raw @products.to_json %>
<% end %>

<%= form_for @invoice, :html => { :class => 'form-horizontal' } do |f| %>

  <% if @invoice.errors.any? %>
    <div id="">
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
        Skjemaet inneholder <%= @invoice.errors.count %> feil. <br><br>
        <ul class="">
          <% @invoice.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <h3>Kundedetaljer</h3>
  <br>

  <%= f.hidden_field :client_id, :value => @invoice.client_id %>


  <div class="form-group">
    <%= f.label :client_name, 'Navn *', class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :client_name, :readonly => true, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :client_email, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :client_email, :readonly => true, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :client_org_nr, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :client_org_nr, :readonly => true, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :client_ref, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :client_ref, :readonly => true, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :client_address, 'Adresse *', class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :client_address, :readonly => true, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :delivery_address, 'Leveringsadresse *', class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :delivery_address, :readonly => true, class:"form-control" %>
    </div>
  </div>

<br><br>

<h3>Kreditnotadetaljer</h3>

  <div class="form-group">
    <%= f.label :invoice_number, 'Kreditnotanummer *', class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.number_field :invoice_number, :readonly => true, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :order_date, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <div class="input-group">
        <div class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></div>
        <%= f.text_field :order_date, 'data-provide' => 'datepicker', 'data-date-format' => "dd/mm/yyyy", 'placeholder' => 'dd/mm/yyyy', 'value' => @invoice.order_date, :readonly => true, class:"form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :delivery_date, 'Leveringsdato *', class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <div class="input-group">
        <div class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></div>
        <%= f.text_field :delivery_date, 'data-provide' => 'datepicker', 'data-date-format' => "dd/mm/yyyy", 'value' => @invoice.delivery_date, :readonly => true, class:"form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :due_date, 'Forfallsdato *', class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <div class="input-group">
        <div class="input-group-addon"><i class="glyphicon glyphicon-calendar"></i></div>
        <%= f.text_field :due_date, 'data-provide' => 'datepicker', 'data-date-format' => "dd/mm/yyyy", 'value' => @invoice.due_date.strftime('%d/%m/%Y'), :readonly => true, class:"form-control" %>
      </div>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :notes, 'Beskrivelse', class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
    <%= f.text_area :notes, class:"form-control", 'placeholder' => 'En beskrivende oppsummering av fakturaen' %>
    </div>
  </div>

  <div id="itemList">
    <%= f.fields_for :invoice_items do |item| %>

      <div class="itempadding grad">
        <h3>Produkt/Tjeneste</h3>

        <div class="form-group">
          <%= item.label :description, 'Beskrivelse *', class:"col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= item.text_field :description, :readonly => true, class:"form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= item.label :quantity, 'Antall *', class:"col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= item.text_field :quantity, class:"form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= item.label :unit, 'Enhet (timer, kg, ...) *', class:"col-sm-3 control-label" %>
          <div class="col-sm-9">
            <%= item.text_field :unit, :readonly => true, class:"form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= item.label :unit_price, 'Pris per enhet *', class:"col-sm-3 control-label" %>
          <div class="col-sm-9">
            <div class="input-group">
                <%= item.text_field :unit_price, class:"form-control" %>
                <div class="input-group-addon">kr</div>
              </div>
          </div>
        </div>

        <div class="form-group">
          <%= item.label :vat, 'MVA *', class:"col-sm-3 control-label" %>
          <div class="col-sm-9">
            <div class="input-group">
              <%= item.text_field :vat, :readonly => true, class:"form-control" %>
              <div class="input-group-addon">%</div>
            </div>
          </div>
        </div>

    <% end %>
  </div>

  <%= f.hidden_field :currency, :value => 'kr' %>
  <%= f.hidden_field :kreditnota, :value => true %>
  <%= f.hidden_field :paid, :value => true %>

  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.submit "Lagre", class:'btn btn-primary', data: { confirm: 'En lagret kreditnota kan ikke slettes eller endres. Er du sikker på at alle felt er korrekt utfyllt?' } %>
      <%= link_to "Avbryt", invoices_path, class:'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/invoices/show.html.erb
<div class="container invoicewidth">

    <div class="row hidden-print">
        <div class="col-sm-12 text-center">
            <div class="btn-group">
                <!-- PDF -->
                <%= link_to invoice_path(@invoice, :format => :pdf), title: "Last ned som PDF", class: "btn btn-default btn-sm" do %>
                  <i class="glyphicon glyphicon-save"> Last ned</i>
                <% end %>
                <!-- Send -->
                <% if @invoice.client.email.blank? %>
                  <%= link_to '#', data: { :confirm => 'Du har ikke lagt inn en epost-adresse for denne kunden.'}, title: "Ingen lagret epostadresse for kunden", class: "btn btn-default btn-sm" do %>
                      <i class="glyphicon glyphicon-ban-circle" style="color: #777"> Send Epost</i>
                    <% end %>
                <% else %>
                  <% if @invoice.sends == 0 %>
                    <%= link_to email_invoice_invoice_path(:id => @invoice.id), { :title => "Send faktura til kunde", :remote => true, 'class' => "btn btn-default btn-sm", 'data-toggle' =>  "modal", 'data-target' => '#modal-invoice-email-window'} do %>
                      <i class="glyphicon glyphicon-send"> Send Epost</i>
                    <% end %>
                  <% else %>
                    <%= link_to email_invoice_invoice_path(:id => @invoice.id), { :title => "Send på nytt", :remote => true, 'class' => "btn btn-default btn-sm", 'data-toggle' =>  "modal", 'data-target' => '#modal-invoice-email-window'} do %>
                      <i class="glyphicon glyphicon-send" style="color: #777"> Send Epost</i>
                    <% end %>
                  <% end %>
                <% end %>
                <!-- Kreditnota -->
                <% if @invoice.kreditnota %>
                  <%= link_to '#', title: "Kan ikke kreditere en kreditnota", class: "btn btn-default btn-sm" do %>
                    <i class="glyphicon glyphicon-ban-circle" style="color: #777"></i>
                  <% end %>
                <% else %>
                  <%= link_to kreditnota_invoice_path(:id => @invoice.id), title: "Lag Kreditnota", class: "btn btn-default btn-sm" do %>
                    <i class="glyphicon glyphicon-remove"> Lag Kreditnota</i>
                  <% end %>
                <% end %>
                <!-- Marker Betalt -->
                <% if @invoice.paid %>
                  <%= link_to set_paid_invoice_path(@invoice, paid: false), title: "Marker som ikke betalt", class: "btn btn-default btn-sm" do %>
                      <i class="glyphicon glyphicon-ok-sign"> Marker Betalt</i><% end %>
                <% else %>
                      <%= link_to set_paid_invoice_path(@invoice, paid: true), title: "Marker som betalt", class: "btn btn-default btn-sm" do %>
                      <i class="glyphicon glyphicon-ok-circle" style="color: #777"> Marker Betalt</i><% end %>
                <% end %>
            </div>
        </div>
    </div>
    <br>
    <div class="panel panel-default">
        <div class="panel-body">
            <%= render partial: 'invoices/partials/invoice_layout' %>
            <br><br><br><br><br><br>
        </div>
    </div>
</div>

app/views/invoices/show.pdf.erb
<%= wicked_pdf_stylesheet_link_tag "application" %>

<div class="pdf-mail">

    <%= render partial: 'invoices/partials/invoice_layout.html.erb' %>

</div>