config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/help'
  get 'static_pages/home'

  resources :products do
    get :product_json, :on => :member
  end

  resources :clients do
    get :client_json, :on => :member
  end

  devise_for :users, :path_prefix => 'auth'
  resources :users, :only => [:show]

  resources :invoices, :except => [:edit, :update, :destroy] do
    get :set_paid,            :on => :member
    get :kreditnota,          :on => :member
    get :email_invoice,       :on => :member
    post :send_email_invoice, :on => :member
  end

  get 'invoice_items/destroy'

  ActiveAdmin.routes(self)
  get 'static_pages/home'

  # Set different roots for guest and logged in user
  authenticated :user do
    root 'invoices#index', :as => 'auth_root'
  end
  root 'static_pages#home'
end

app/models/client.rb
# A Client is a recipient of one or more invoices.
# Created by a User or created automatically by Invoice controller.
class Client < ActiveRecord::Base
  # Sort by name as default
  default_scope { order('name ASC') }

  # Associations
  belongs_to :user
  has_many :invoices, :dependent => :restrict_with_exception

  # Validations
  validates :user,             :presence => true
  validates :name,             :presence => true
  validates :address,          :presence => true
  validates :delivery_address, :presence => true

  # Returns the sum of all invoices sent to the client as a float
  def total_invoiced
    total = 0.0
    invoices.each do |i|
      i.kreditnota ? total -= i.total : total += i.total
    end
    total
  end

  def self.select_map
    all.map { |c| [c.name, c.id] }
  end
end

app/controllers/clients_controller.rb
# Actions related to clients
class ClientsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @clients = current_user.clients
  end

  # rubocop:disable Metrics/AbcSize
  # rubocop:disable Metrics/MethodLength
  def show
    @client = current_user.clients.find(params[:id])
    if params[:filter] == 'unpaid'
      @invoice_list = @client.invoices.unpaid.paginate(
        :per_page => 25, :page => params[:page])
    elsif params[:filter] == 'overdue'
      @invoice_list = @client.invoices.overdue.paginate(
        :per_page => 25, :page => params[:page])
    else
      @invoice_list = @client.invoices.paginate(
        :per_page => 25, :page => params[:page])
    end
  end
  # rubocop:enable Metrics/AbcSize
  # rubocop:enable Metrics/MethodLength

  def new
    @client = current_user.clients.new
  end

  def create
    @client = current_user.clients.new(client_params)
    if @client.save
      redirect_to clients_path, :notice => 'Kunde Opprettet!'
    else
      render 'new'
    end
  end

  def edit
    @client = current_user.clients.find(params[:id])
  end

  def update
    @client = current_user.clients.find(params[:id])
    if @client.update(client_params)
      redirect_to clients_path, :notice => 'Kunde Oppdatert'
    else
      render 'edit'
    end
  end

  def destroy
    client = current_user.clients.find(params[:id])
    begin
      client.destroy
      flash[:notice] = 'Kunde slettet'
    rescue
      flash[:alert] = 'Du kan ikke slette en kunde som har motatt fakturaer'
    end
    redirect_to clients_path
  end

  def client_json
    client = current_user.clients.find(params[:id])
    render :json => client
  end

  private

  def client_params
    params.require(:client).permit(:name, :address, :delivery_address,
                                   :email, :user_id, :ref, :org_nr)
  end
end

app/views/clients/edit.html.erb
<h1>Rediger <%= @client.name %></h1><br>

<%= form_for @client, :html => { :class => 'form-horizontal' } do |f| %>

  <%= render 'shared/client_error_messages' %>

  <div class="form-group">
    <%= f.label :name, 'Navn *', class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :name, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :org_nr, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :org_nr, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :ref, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :ref, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
    <%= f.text_field :address, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :delivery_address, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
    <%= f.text_field :delivery_address, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
    <%= f.text_field :email, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.submit "Oppdater", class:'btn btn-primary'%>
      <%= link_to "Avbryt", clients_path, class:'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/clients/index.html.erb
  <h1>Kunder</h1><br>
  <p><%= link_to '+ Ny Kunde', new_client_path, class:'btn btn-default btn-block' %></p><br>

<% if @clients.count == 0 %>
  <p>Her vil du se dine lagrede kunder/kontakter. Det vil etterhvert bli mulig å velge mellom lagrede kunder eller å skrive inn info direkte når du oppretter en faktura, men foreløpig er du nødt til å lagre en kunde her før du kan fakturere vedkommende.</p>
<% else %>
  <div class="table-responsive">
    <table class="table table-condensed table-striped">
      <thead>
        <tr>
          <th>Navn</th>
          <th>Adresse</th>
          <th>Email</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @clients.each do |client| %>
          <tr id="client_<%= client.id %>">
            <td><%= link_to client.name, client %></td>
            <td><%= client.address %></td>
            <td><%= client.email %></td>
            <td class="text-right" style="min-width: 100px">
              <div class="btn-group">
                <%= link_to client, class: "btn btn-default btn-xs", id: 'show' do %>
                  <i class="glyphicon glyphicon-zoom-in"></i>
                <% end %>&nbsp;
                <%= link_to edit_client_path(client), class: "btn btn-default btn-xs", id: 'edit' do %>
                  <i class="glyphicon glyphicon-pencil"></i>
                <% end %>&nbsp;
                <%= link_to client, method: :delete, data: { confirm: 'Sikker? Sletting kan ikke angres. (Dersom kunden allerede har assosierte fakturaer vil sletting ikke være mulig.)' }, class: "btn btn-default btn-xs", id: 'delete' do %>
                  <i class="glyphicon glyphicon-trash"></i>
                <% end %>
              </div>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>

<!-- IKON FORKLARINGER -->
<div class="text-muted text-center">
  <small>
  <ul class="list-inline">
    <li><i class="glyphicon glyphicon-zoom-in"></i>&nbsp;&nbsp;Se kundeinfo.</li>
    <li><i class="glyphicon glyphicon-pencil"></i>&nbsp;&nbsp;Rediger kunde.</li>
    <li><i class="glyphicon glyphicon-trash"></i>&nbsp;&nbsp;Slett kunde. (Kun mulig for kunder uten fakturaer.)</li>
  </ul>
  </small>
</div>
<% end %>

app/views/clients/new.html.erb
<h1>Ny Kunde</h1><br>

<%= form_for @client, :html => { :class => 'form-horizontal' } do |f| %>

  <%= render 'shared/client_error_messages' %>

  <div class="form-group">
    <%= f.label :name, 'Navn *', class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :name, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :org_nr, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :org_nr, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :ref, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :ref, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :address, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
    <%= f.text_field :address, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :delivery_address, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
    <%= f.text_field :delivery_address, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :email, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
    <%= f.text_field :email, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.submit "Opprett Kunde", class:'btn btn-primary'%>
      <%= link_to "Avbryt", clients_path, class:'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/clients/show.html.erb
<h1><%= @client.name %></h1><br>
<p><%= link_to 'Rediger Kunde', edit_client_path(@client), class:'btn btn-default btn-block' %></p><br>

<div class="row">
  <div class="col-sm-12">
    <table class="table table-condensed table-striped table-no-border">
      <tr>
        <td>Org.nr: </td>
        <td><%= @client.org_nr %></td>
      </tr>
      <tr>
        <td>Deres ref: </td>
        <td><%= @client.ref %></td>
      </tr>
      <tr>
        <td>Adresse: </td>
        <td><%= @client.address %></td>
      </tr>
      <tr>
        <td>Leveringsadresse: </td>
        <td><%= @client.delivery_address %></td>
      </tr>
      <tr>
        <td>Epost: </td>
        <td><%= @client.email %></td>
      </tr>
      <tr>
        <td>Totalt fakturert: </td>
        <td><%= number_to_currency(@client.total_invoiced) %></td>
      </tr>
    </table>
  </div>

</div>
<hr class="divider">
<div class="clearfix"></div>
<h3>Fakturaoversikt</h3>
<div id="invoice-list">
  <%= render partial: 'invoices/partials/invoice_list' %>
</div>