config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/help'
  get 'static_pages/home'

  resources :products do
    get :product_json, :on => :member
  end

  resources :clients do
    get :client_json, :on => :member
  end

  devise_for :users, :path_prefix => 'auth'
  resources :users, :only => [:show]

  resources :invoices, :except => [:edit, :update, :destroy] do
    get :set_paid,            :on => :member
    get :kreditnota,          :on => :member
    get :email_invoice,       :on => :member
    post :send_email_invoice, :on => :member
  end

  get 'invoice_items/destroy'

  ActiveAdmin.routes(self)
  get 'static_pages/home'

  # Set different roots for guest and logged in user
  authenticated :user do
    root 'invoices#index', :as => 'auth_root'
  end
  root 'static_pages#home'
end

app/models/product.rb
# Products is a representation of an item or service
# that can be transferred to an invoice item
class Product < ActiveRecord::Base
  # Sort by product number as default
  default_scope { order('product_number ASC') }

  # Associations
  belongs_to :user

  # Validations
  validates :user,           :presence     => true
  validates :description,    :presence     => true
  validates :unit,           :presence     => true
  validates :product_number, :presence     => true
  validates :price,          :presence     => true,
                             :numericality => { :message =>
                                                'må være et tall.' },
                             :format       => /\A\d+(\.\d{1,2})?\z/,
                             :allow_blank  => false,
                             :on           => :create
  validates :vat,            :presence     => true,
                             :numericality => { :message =>
                                                'må være heltall.' },
                             :format       => /\A\d{1,2}\z/,
                             :allow_blank  => false,
                             :on           => :create

  # Replaces comma with period and strips spaces
  def price=(price)
    price = price.to_s.gsub(',', '.')
    price = price.gsub(' ', '')
    self[:price] = price
  end

  # Returns product number and description as string
  def product_with_number
    "[#{product_number}] #{description}"
  end
end

app/controllers/products_controller.rb
# Actions relating to products
class ProductsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource

  def index
    @products = current_user.products
  end

  def show
    @product = current_user.products.find(params[:id])
  end

  def new
    @product = current_user.products.new
  end

  def create
    @product = current_user.products.new(product_params)
    if @product.save
      redirect_to products_path, :notice => 'Produkt er opprettet!'
    else
      render 'new'
    end
  end

  def edit
    @product = current_user.products.find(params[:id])
  end

  def update
    @product = current_user.products.find(params[:id])
    if @product.update(product_params)
      redirect_to products_path, :notice => 'Produkt Oppdatert'
    else
      render 'edit'
    end
  end

  def destroy
    product = current_user.products.find(params[:id])
    begin
      product.destroy
      flash[:notice] = 'Produkt slettet'
    rescue
      flash[:alert] = 'Kunne ikke slette produkt'
    end
    redirect_to product
  end

  def product_json
    product = current_user.products.find(params[:id])
    render :json => product
  end

  private

  def product_params
    params.require(:product).permit(:product_number, :description,
                                    :unit, :price, :vat)
  end
end

app/views/products/edit.html.erb
<h1>Nytt Produkt</h1><br>

<%= form_for @product, :html => { :class => 'form-horizontal' } do |f| %>

  <%= render 'shared/product_error_messages' %>

  <p>Alle felt må fylles ut.</p>

  <div class="form-group">
    <%= f.label :product_number, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :product_number, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :description, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :unit, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.text_field :unit, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
    <%= f.text_field :price, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :vat, class:"col-sm-2 control-label" %>
    <div class="col-sm-10">
      <%= f.select :vat, [['0%', 0], ['8%', 8], ['15%', 15], ['25%', 25]], {include_blank: "Velg mva-sats"}, { :class => 'form-control' } %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= f.submit "Oppdater Produkt", class:'btn btn-primary'%>
      <%= link_to "Avbryt", products_path, class:'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/products/index.html.erb
<h1>Produkter</h1><br>

<p><%= link_to '+ Nytt Produkt', new_product_path, class:'btn btn-default btn-block' %></p><br>

<% if @products.count == 0 %>
    <p>
        Her kan du lagre varer og tjenester som du ofte fakturerer for. Oppføringer i ditt produktregister vil være tilgjengelige som hurtigvalg når du lager en ny faktura.
    </p>

<% else %>

    <div class="table-responsive">
        <table class="table table-condensed table-striped">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Beskrivelse</th>
                    <th>Enhet</th>
                    <th>MVA</th>
                    <th class="text-right">Pris</th>
                    <th></th>
                </tr>
            </thead>

            <tbody>
                <% @products.each do |product| %>
                    <tr id="product_<%= product.id %>">
                        <td><%= product.product_number %></td>
                        <td><%= link_to product.description, product %></td>
                        <td><%= product.unit %></td>
                        <td><%= product.vat %> %</td>
                        <td class="text-right"><%= number_with_precision(product.price, :precision => 2) %> kr</td>
                        <td class="text-right" style="min-width: 100px">
                            <div class="btn-group">
                            <%= link_to product, class: "btn btn-default btn-xs", id: 'show' do %>
                                <i class="glyphicon glyphicon-zoom-in"></i>
                            <% end %>&nbsp;
                            <%= link_to edit_product_path(product), class: "btn btn-default btn-xs", id: 'edit' do %>
                                <i class="glyphicon glyphicon-pencil"></i>
                            <% end %>&nbsp;
                            <%= link_to product, method: :delete, data: {confirm: 'Sikker? Sletting kan ikke angres.' }, class: "btn btn-default btn-xs", id: 'delete' do %>
                                <i class="glyphicon glyphicon-trash"></i>
                            <% end %>
                        </td>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>


    <!-- IKON FORKLARINGER -->
    <div class="text-muted text-center">
        <small>
            <ul class="list-inline">
                <li><i class="glyphicon glyphicon-zoom-in"></i>&nbsp;&nbsp;Se produktinfo.</li>
                <li><i class="glyphicon glyphicon-pencil"></i>&nbsp;&nbsp;Rediger produkt.</li>
                <li><i class="glyphicon glyphicon-trash"></i>&nbsp;&nbsp;Slett produkt.</li>
            </ul>
        </small>
    </div>

<% end %>

app/views/products/new.html.erb
<h1>Nytt Produkt</h1><br>

<%= form_for @product, :html => { :class => 'form-horizontal' } do |f| %>

  <%= render 'shared/product_error_messages' %>

  <p>Alle felt må fylles ut.</p>

  <div class="form-group">
    <%= f.label :product_number, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :product_number, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :description, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :description, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :unit, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.text_field :unit, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :price, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
    <%= f.text_field :price, class:"form-control" %>
    </div>
  </div>

  <div class="form-group">
    <%= f.label :vat, class:"col-sm-3 control-label" %>
    <div class="col-sm-9">
      <%= f.select :vat, [['0%', 0], ['8%', 8], ['15%', 15], ['25%', 25]], {include_blank: "Velg mva-sats"}, { :class => 'form-control' } %>
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-3 col-sm-9">
      <%= f.submit "Opprett Produkt", class:'btn btn-primary'%>
      <%= link_to "Avbryt", products_path, class:'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/products/show.html.erb
<h1>Prod.nr <%= @product.product_number %></h1><br>
<p><%= link_to 'Rediger Produkt', edit_product_path(@product), class:'btn btn-default btn-block' %></p><br>

<div class="row">
  <div class="col-sm-12">
    <table class="table table-condensed table-striped table-no-border">
      <tr>
        <td>Produktnummer: </td>
        <td><%= @product.product_number %></td>
      </tr>
      <tr>
        <td>Beskrivelse: </td>
        <td><%= @product.description %></td>
      </tr>
      <tr>
        <td>Enhet: </td>
        <td><%= @product.unit %></td>
      </tr>
      <tr>
        <td>MVA-sats: </td>
        <td><%= @product.vat %></td>
      </tr>
      <tr>
        <td>Pris: </td>
        <td><%= number_with_precision(@product.price, :precision => 2) %> kr</td>
      </tr>
    </table>
  </div>
</div>