config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/help'
  get 'static_pages/home'

  resources :products do
    get :product_json, :on => :member
  end

  resources :clients do
    get :client_json, :on => :member
  end

  devise_for :users, :path_prefix => 'auth'
  resources :users, :only => [:show]

  resources :invoices, :except => [:edit, :update, :destroy] do
    get :set_paid,            :on => :member
    get :kreditnota,          :on => :member
    get :email_invoice,       :on => :member
    post :send_email_invoice, :on => :member
  end

  get 'invoice_items/destroy'

  ActiveAdmin.routes(self)
  get 'static_pages/home'

  # Set different roots for guest and logged in user
  authenticated :user do
    root 'invoices#index', :as => 'auth_root'
  end
  root 'static_pages#home'
end

app/views/layouts/partials/_footer.html.erb
<div class="row">
    <div class="col-sm-4">
        <h4>Bruksvillkår</h4>
        <p>
            Fakturaer laget med Bare Faktura oppfyller alle offentlige krav til form og innhold. Du er likevel selv ansvarlig for at dine fakturaer er gyldige, og Bare Faktura kan ikke holdes ansvarlig for eventuelle regelbrudd. Ved å bruke tjenesten aksepterer du dette.
        </p>
    </div>
    <div class="col-sm-4">
        <h4>Kontakt</h4>
        <p>
            Dersom du har spørsmål, oppdager feil, ønsker nye funksjoner eller bare vil si hei, setter vi stor pris på en epost til <%= mail_to 'post@barefaktura.no' %>.
        </p>
    </div>
    <div class="col-sm-12 text-center">
        <p>&copy; 2015 BareFaktura.no</p>
        <%= debug(params) if Rails.env.development? %>
    </div>
</div>

app/views/layouts/partials/_modals.html.erb
<!-- Send invoice email modal -->
<div class="modal fade" id="modal-invoice-email-window" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog" id="email-invoice-modal"></div>
</div>

<!-- Loading Modal -->
<div class="loading-modal"><!-- Place at bottom of page --></div>

app/views/layouts/partials/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top navbar-custom" role="navigation">
  <div class="container">
    <div class="container-nav">

      <div class="navbar-header">

        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= signed_in? ? invoices_path : root_path %>">BareFaktura</a>
      </div>

      <div id="navbar" class="collapse navbar-collapse">

        <ul class="nav navbar-nav">
          <% if signed_in? %>
            <li class="<%= params[:controller] == 'invoices' && params[:action] != 'show' ? 'active' : '' %>"><%= link_to invoices_path do %>Faktura<% end %></li>
            <li class="<%= params[:controller] == 'clients' ? 'active' : '' %>"><%= link_to 'Kunder', clients_path %></li>
            <li class="<%= params[:controller] == 'products' ? 'active' : '' %>"><%= link_to 'Produkter', products_path %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>

            <li class="dropdown">
              <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="navbar-link">
                <%= current_user.name %> <span class="caret"></span>
              </a>

              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Min Profil", current_user %></li>
                <li><%= link_to 'Hjelp', static_pages_help_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Logg Ut", destroy_user_session_path, method: :delete %></li>
                <% if current_user.role? :administrator %>
                  <li><%= link_to "Admin Side", admin_root_path %></li>
                <% end %>
              </ul>
            </li>
          <% else %>
              <li ><%= link_to 'Logg Inn', new_user_session_path, class:"navbar-link" %></li>
              <li><%= link_to 'Opprett Konto', new_user_registration_path, class:"navbar-link" %></li>
              <li><%= link_to 'Hjelp', static_pages_help_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</nav>

app/views/layouts/partials/_navigation_landing.html.erb
<nav class="navbar navbar-default navbar-static-top navbar-custom navbar-landing" role="navigation">
  <div class="container">
    <div class="container-nav">

      <div class="navbar-header">

        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="<%= signed_in? ? invoices_path : root_path %>">BareFaktura</a>
      </div>

      <div id="navbar" class="collapse navbar-collapse">

        <ul class="nav navbar-nav">
          <% if signed_in? %>
            <li class="<%= params[:controller] == 'invoices' ? 'active' : '' %>"><%= link_to 'Faktura', invoices_path %></li>
            <li class="<%= params[:controller] == 'clients' ? 'active' : '' %>"><%= link_to 'Kunder', clients_path %></li>
            <li class="<%= params[:controller] == 'products' ? 'active' : '' %>"><%= link_to 'Produkter', products_path %></li>
          <% end %>
        </ul>

        <ul class="nav navbar-nav navbar-right">
          <% if signed_in? %>

            <li class="dropdown">
              <a href="#" data-toggle="dropdown" role="button" aria-expanded="false" class="navbar-link">
                <%= current_user.name %> <span class="caret"></span>
              </a>

              <ul class="dropdown-menu" role="menu">
                <li><%= link_to "Min Profil", current_user %></li>
                <li><%= link_to 'Hjelp', static_pages_help_path %></li>
                <li class="divider"></li>
                <li><%= link_to "Logg Ut", destroy_user_session_path, method: :delete %></li>
                <% if can? :update, @user %>
                  <li><%= link_to "Admin Side", admin_root_path %></li>
                <% end %>
              </ul>
            </li>
          <% else %>
              <li ><%= link_to 'Logg Inn', new_user_session_path, class:"navbar-link" %></li>
              <li><%= link_to 'Opprett Konto', new_user_registration_path, class:"navbar-link" %></li>
              <li><%= link_to 'Hjelp', static_pages_help_path %></li>
          <% end %>
        </ul>
      </div><!--/.nav-collapse -->
    </div>
  </div>
</nav>